# Generated by Django 3.0.3 on 2020-05-16 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0002_auto_20200504_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Recoverd',
            new_name='Recovered',
        ),
    ]
