# Generated by Django 3.0.3 on 2020-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Country',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='ListOfCountries',
        ),
    ]
